--- cria tabela oracle para teste

create table SALES_TRANSACTIONS (
    TRANSACTION_ID number PRIMARY KEY,
    CUSTOMER_ID number not null,
    AMOUNT number(10,2) not null,
    TRANSACTION_DATE date not null
);



--- faz carga para testes

insert into SALES_TRANSACTIONS (TRANSACTION_ID, CUSTOMER_ID, AMOUNT, TRANSACTION_DATE) values (1, 101, 150.75, TO_DATE('2024-02-01', 'YYYY-MM-DD'));
insert into SALES_TRANSACTIONS (TRANSACTION_ID, CUSTOMER_ID, AMOUNT, TRANSACTION_DATE) values (2, 102, -89.50, TO_DATE('2024-02-02', 'YYYY-MM-DD'));
insert into SALES_TRANSACTIONS (TRANSACTION_ID, CUSTOMER_ID, AMOUNT, TRANSACTION_DATE) values (3, 103, 200.99, TO_DATE('2024-02-03', 'YYYY-MM-DD'));
insert into SALES_TRANSACTIONS (TRANSACTION_ID, CUSTOMER_ID, AMOUNT, TRANSACTION_DATE) values (4, 104, -75.25, TO_DATE('2024-02-04', 'YYYY-MM-DD'));
insert into SALES_TRANSACTIONS (TRANSACTION_ID, CUSTOMER_ID, AMOUNT, TRANSACTION_DATE) values (5, 105, 300.40, TO_DATE('2024-02-05', 'YYYY-MM-DD'));
insert into SALES_TRANSACTIONS (TRANSACTION_ID, CUSTOMER_ID, AMOUNT, TRANSACTION_DATE) values (6, 106, 150.00, TO_DATE('2024-02-06', 'YYYY-MM-DD'));
insert into SALES_TRANSACTIONS (TRANSACTION_ID, CUSTOMER_ID, AMOUNT, TRANSACTION_DATE) values (7, 107, -95.10, TO_DATE('2024-02-07', 'YYYY-MM-DD'));
insert into SALES_TRANSACTIONS (TRANSACTION_ID, CUSTOMER_ID, AMOUNT, TRANSACTION_DATE) values (8, 108, -500.75, TO_DATE('2024-02-08', 'YYYY-MM-DD'));
insert into SALES_TRANSACTIONS (TRANSACTION_ID, CUSTOMER_ID, AMOUNT, TRANSACTION_DATE) values (9, 109, 210.30, TO_DATE('2024-02-09', 'YYYY-MM-DD'));
insert into SALES_TRANSACTIONS (TRANSACTION_ID, CUSTOMER_ID, AMOUNT, TRANSACTION_DATE) values (10, 110, 125.60, TO_DATE('2024-02-10', 'YYYY-MM-DD'));

COMMIT;


--- confere a carga

select count(*) from SALES_TRANSACTIONS;

